version: '3.7'

services:

    ldap:
        ports:
        - 389:389

    mail:
      container_name: smartsla_mail_dev
      image: tvial/docker-mailserver
      hostname: mail
      domainname: open-paas.org
      ports:
          - "20025:25"
          - "20143:143"
          - "20587:587"
          - "20993:993"
      volumes:
          - /var/mail
          - /var/mail-state
          - /tmp/docker-mailserver/
          - ./assets/mail_conf/main.cf:/etc/postfix/main.cf
          - ./assets/mail_conf/10-ssl.conf:/etc/dovecot/conf.d/10-ssl.conf
          - ./assets/mail_conf/10-auth.conf:/etc/dovecot/conf.d/10-auth.conf
          - ./assets/mail_conf/dovecot-ldap.conf.ext:/etc/dovecot/dovecot-ldap.conf.ext
      environment:
          - ENABLE_SPAMASSASSIN=1
          - SPAMASSASSIN_SPAM_TO_INBOX=1
          - ENABLE_CLAMAV=1
          - ENABLE_FAIL2BAN=1
          - ENABLE_POSTGREY=1
          - ONE_DIR=1
          - DMS_DEBUG=0
          - ENABLE_LDAP=1
          - LDAP_SERVER_HOST=ldap
          - LDAP_SEARCH_BASE=ou=users,dc=openpaas,dc=org
          - LDAP_BIND_DN=cn=openpaas,ou=accounts,dc=openpaas,dc=org
          - LDAP_BIND_PW=openpaas
          - LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE))
          - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailEnabled=TRUE))
          - LDAP_QUERY_FILTER_ALIAS=(|(&(mailAlias=%s)(objectClass=PostfixBookMailForward))(&(mailAlias=%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE)))
          - LDAP_QUERY_FILTER_DOMAIN=(|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailalias=*@%s)(objectClass=PostfixBookMailForward)))
          - DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
          - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))
          - ENABLE_SASLAUTHD=1
          - SASLAUTHD_MECHANISMS=ldap
          - SASLAUTHD_LDAP_SERVER=ldap
          - SASLAUTHD_LDAP_BIND_DN=cn=openpaas,ou=accounts,dc=openpaas,dc=org
          - SASLAUTHD_LDAP_PASSWORD=openpaas
          - SASLAUTHD_LDAP_SEARCH_BASE=ou=users,dc=openpaas,dc=org
          - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%U))
          - POSTMASTER_ADDRESS=postmaster@open-paas.org
          - POSTFIX_MESSAGE_SIZE_LIMIT=100000000

    webmail:
      container_name: smartsla_webmail_dev
      image: robbertkl/roundcube
      ports:
          - "20087:80"
      volumes:
          - ./assets/webmail_conf/config.inc.php:/var/www/config/config.inc.php
      environment:
          - ROUNDCUBE_DEFAULT_HOST=smartsla_mail_dev
          - ROUNDCUBE_SMTP_SERVER=smartsla_mail_dev
          - ROUNDCUBE_SMTP_PORT=25
      labels:
        - "traefik.enable=true"
        - "traefik.openpaas.frontend.rule=Host:webmail.smartsla.local"


    ldap-init:
        image: linagora/openpaas-ldap-init:1.2.2
        # build: ../openpaas-ldap-init-dockerfile
        depends_on:
        - ldap
        environment:
        # init config for dev (you must override them in every mode)
        - LDAP_HOST=ldap
        - LDAP_PORT=389
        - LDAP_BIND_PW=adminopenpaas
        # lemonldap config for dev (you must override them in every mode)
        - TEMPLATE_LDAP_BIND_DN=cn=lemonldap,ou=accounts,dc=openpaas,dc=org
        - TEMPLATE_LDAP_BIND_PW=adminopenpaas
        - TEMPLATE_LDAP_URI=ldap://ldap:389
        # lemonldap config for dev (no need to override them in production mode)
        - OPENPAAS_BIND_DN=cn=openpaas,ou=accounts,dc=openpaas,dc=org
        - OPENPAAS_BIND_PW=openpaas
        - LINSHARE_BIND_DN=cn=linshare,ou=accounts,dc=openpaas,dc=org
        - LINSHARE_BIND_PW=linshare
        - LOAD_USERS=1
        - DEBUG=0
        volumes:
        - ./assets/conf/ldap-init/modify-postfix-user.ldif:/linagora/data/ldifs/custom/users.ldif